//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long activity_log_id { get; set; }
        public System.Guid guid { get; set; }
        public int vendor_master_id { get; set; }
        public int app_user_id { get; set; }
        public string user_name { get; set; }
        public string heading { get; set; }
        public string heading_class { get; set; }
        public string activity { get; set; }
        public string icon { get; set; }
        public string icon_class { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
