//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftMaster
    {
        public int draft_master_id { get; set; }
        public System.Guid guid { get; set; }
        public int production_id { get; set; }
        public string batch_number { get; set; }
        public int parent_item_master_id { get; set; }
        public string items_name { get; set; }
        public bool left_over_size_availabel { get; set; }
        public string left_over_size { get; set; }
        public int draft_quantity { get; set; }
        public string draft_status { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
