//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public long exception_log_id { get; set; }
        public System.Guid guid { get; set; }
        public string exception_message { get; set; }
        public Nullable<System.DateTime> exception_log_date { get; set; }
        public string exception_source { get; set; }
        public string user_agent { get; set; }
        public string trace_log { get; set; }
        public string param_value { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
