//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        public int followup_id { get; set; }
        public System.Guid guid { get; set; }
        public int lead_header_id { get; set; }
        public System.DateTime followup_date { get; set; }
        public string followup_text { get; set; }
        public System.DateTime next_followup_date { get; set; }
        public string special_remarks { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
