//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int menu_master_id { get; set; }
        public System.Guid guid { get; set; }
        public string display_name { get; set; }
        public string page_url { get; set; }
        public int parent_id { get; set; }
        public Nullable<int> parent_order { get; set; }
        public Nullable<int> child_order { get; set; }
        public string cssclass { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
