//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMaster
    {
        public int party_master_id { get; set; }
        public System.Guid guid { get; set; }
        public string party_name { get; set; }
        public string party_contact_person { get; set; }
        public string party_phoneno { get; set; }
        public string party_email { get; set; }
        public string party_gst { get; set; }
        public string party_address { get; set; }
        public string party_state { get; set; }
        public string party_city { get; set; }
        public string party_pincode { get; set; }
        public string party_region { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
        public decimal tough_discount_precentage { get; set; }
        public int tough_billing_precentage { get; set; }
        public decimal lami_discount_precentage { get; set; }
        public int lami_billing_precentage { get; set; }
        public int netrate_billing_precentage { get; set; }
    }
}
