//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDfgPrint
    {
        public int process_dfg_print_id { get; set; }
        public System.Guid guid { get; set; }
        public int item_master_id { get; set; }
        public string item_brand { get; set; }
        public string item_model { get; set; }
        public string item_type_name { get; set; }
        public string item_glass_color { get; set; }
        public string sale_header_master_id { get; set; }
        public string party_master_id { get; set; }
        public string batch_number { get; set; }
        public int production_quantity { get; set; }
        public System.DateTime dfg_print_started_on { get; set; }
        public System.DateTime dfg_print_ended_on { get; set; }
        public string item_thickness { get; set; }
        public string item_sheet_size { get; set; }
        public int sheet_issued { get; set; }
        public int target_pcs_from_sheet_issued { get; set; }
        public int actual_pcs_from_sheet_issued { get; set; }
        public string draft_size { get; set; }
        public int target_pcs_from_draft_size { get; set; }
        public int actual_pcs_from_draft_size { get; set; }
        public int pcs_from_rejection { get; set; }
        public int actual_pcs_from_rejection { get; set; }
        public int broken_sheets_in_crate { get; set; }
        public int broken_no_of_sheet { get; set; }
        public int broken_pcs_cut_from_sheet { get; set; }
        public string broken_left_over_size { get; set; }
        public int total_received { get; set; }
        public int total_broken { get; set; }
        public int total_reject { get; set; }
        public int total_pcs_transferred { get; set; }
        public int signature { get; set; }
        public string breakage_pcs_number { get; set; }
        public string breakage_reason { get; set; }
        public string reject_pcs_number { get; set; }
        public string reject_reason { get; set; }
        public string remarks { get; set; }
        public string dfg_status { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
