//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlanning
    {
        public int production_planning_id { get; set; }
        public System.Guid guid { get; set; }
        public int item_master_id { get; set; }
        public string item_brand { get; set; }
        public string item_model { get; set; }
        public string item_type_name { get; set; }
        public string item_glass_color { get; set; }
        public int party_master_id { get; set; }
        public int order_quantity { get; set; }
        public int overall_total_item { get; set; }
        public int factory_stock { get; set; }
        public int shortage { get; set; }
        public int stock_max_level { get; set; }
        public int production_quantity { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
