//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int purchase_item_id { get; set; }
        public System.Guid guid { get; set; }
        public int purchase_header_id { get; set; }
        public int item_master_id { get; set; }
        public int supplier_master_id { get; set; }
        public int purchase_item_type_id { get; set; }
        public string purchase_item_name { get; set; }
        public int purchase_item_quantity { get; set; }
        public int purchase_item_price { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
