//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int sale_item_id { get; set; }
        public System.Guid guid { get; set; }
        public int sale_header_id { get; set; }
        public int item_master_id { get; set; }
        public int party_master_id { get; set; }
        public int sale_item_type_id { get; set; }
        public string sale_item_type_title { get; set; }
        public string sale_item_name { get; set; }
        public int sale_item_quantity { get; set; }
        public decimal sale_item_price { get; set; }
        public decimal sale_item_price_2 { get; set; }
        public decimal sale_item_net_price { get; set; }
        public decimal item_weight { get; set; }
        public int item_gst_percentage { get; set; }
        public string item_unit { get; set; }
        public decimal item_discount_percentage { get; set; }
        public decimal item_discount_amount { get; set; }
        public decimal item_bill_percentage { get; set; }
        public decimal item_amount { get; set; }
        public decimal item_bill_rate { get; set; }
        public decimal item_bill_amount { get; set; }
        public decimal item_gst_amount { get; set; }
        public decimal item_final_amount { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
