//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIssuanceHeader
    {
        public int stock_issuance_header_id { get; set; }
        public System.Guid guid { get; set; }
        public int items_total_quantity { get; set; }
        public decimal items_total_amount { get; set; }
        public string item_remarks { get; set; }
        public System.DateTime item_require_date { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
