//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourExpenseItem
    {
        public int tour_expense_item_id { get; set; }
        public int tour_expense_header_id { get; set; }
        public int tour_master_id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime expense_date { get; set; }
        public int expense_food { get; set; }
        public int expense_hotel { get; set; }
        public int expense_conveyance { get; set; }
        public int expense_misc { get; set; }
        public int expense_total_item { get; set; }
        public int expense_total_approved_item { get; set; }
        public int approved_by { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
        public string expense_image { get; set; }
    }
}
