//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGradeMaster
    {
        public int tourgrade_master_id { get; set; }
        public System.Guid guid { get; set; }
        public string tourgrade_name { get; set; }
        public decimal tourgrade_perday_transport { get; set; }
        public decimal tourgrade_perday_food { get; set; }
        public decimal tourgrade_perday_hotel { get; set; }
        public decimal tourgrade_perday_misc { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
