//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemListWithModelAndGlassColor
    {
        public int item_master_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string modelwithglass { get; set; }
        public string item_type_name { get; set; }
        public string thickness { get; set; }
        public string plant_name { get; set; }
        public int plant_no { get; set; }
        public string category { get; set; }
        public string segment { get; set; }
        public int stock_max_level { get; set; }
        public string price { get; set; }
        public string price_2 { get; set; }
        public int factory_ready_stock { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
