//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPurchaseHeaderSupplierDetail
    {
        public int purchase_header_id { get; set; }
        public System.Guid guid { get; set; }
        public int supplier_master_id { get; set; }
        public int purchase_items_quantity { get; set; }
        public decimal purchase_items_total_amount { get; set; }
        public string purchase_items_payment_by { get; set; }
        public string purchase_items_reference_number { get; set; }
        public decimal purchase_items_pay_amount { get; set; }
        public decimal purchase_items_pending_amount { get; set; }
        public Nullable<decimal> purchase_item_discount { get; set; }
        public string purchase_item_remarks { get; set; }
        public System.DateTime purchase_item_date { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
        public string supplier_name { get; set; }
        public string supplier_contact_person { get; set; }
        public string supplier_phoneno { get; set; }
        public string supplier_email { get; set; }
        public string supplier_gst { get; set; }
        public string supplier_address { get; set; }
        public string supplier_state { get; set; }
        public string supplier_city { get; set; }
        public string supplier_pincode { get; set; }
        public string supplier_region { get; set; }
    }
}
