//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xp_CustomerRequestHeader
    {
        public int xp_customer_request_header_id { get; set; }
        public System.Guid guid { get; set; }
        public int customer_master_id { get; set; }
        public string customer_name { get; set; }
        public string customer_phone { get; set; }
        public int purchase_items_quantity { get; set; }
        public string remarks { get; set; }
        public string request_status { get; set; }
        public System.DateTime purchase_item_date { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
