//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xp_TimeSheetChild
    {
        public int time_sheet_child_id { get; set; }
        public System.Guid guid { get; set; }
        public int staff_master_id { get; set; }
        public string staff_name { get; set; }
        public int project_id { get; set; }
        public string project_name { get; set; }
        public System.DateTime time_sheet_date { get; set; }
        public int time_sheet_header_id { get; set; }
        public string hours { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public int modified_by { get; set; }
        public string user_ip { get; set; }
        public bool is_active { get; set; }
    }
}
